version: '3'

services:
  db:
    restart: always
    image: "postgres:13-alpine"
    restart: always
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backands_network

  web_api:
    restart: always
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    networks:
      - backands_network
    depends_on: 
      - db
    # ports:
    #   - 8080:8080
    
  server:
    restart: always
    build: ./server_nginx/.
    volumes:
      - ./server_nginx/html_files/:/usr/share/nginx/html
    depends_on:
      - web_api 
    networks:
      - backands_network
    ports:
      - "80:80"
      # - 8000:80
      # - 443:443

networks:
  backands_network:
    driver: bridge
