"""098

Revision ID: 1a0e81c95341
Revises: 6a608eea07fa
Create Date: 2021-01-14 22:08:09.118367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0e81c95341'
down_revision = '6a608eea07fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
