"""543ytjhfgf

Revision ID: 1c3d22787f00
Revises: a286e4d95b28
Create Date: 2021-01-14 22:03:16.275234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3d22787f00'
down_revision = 'a286e4d95b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
