"""New revisiond

Revision ID: 2047eccea9a8
Revises: 5719a8391766
Create Date: 2020-12-04 23:14:13.785796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2047eccea9a8'
down_revision = '5719a8391766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rating'], ['rating.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.drop_constraint('users_rating_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'rating_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_rating_id_fkey', 'users', 'rating', ['rating_id'], ['id'])
    op.drop_table('association')
    # ### end Alembic commands ###
