"""New revision6

Revision ID: 2896a2b84175
Revises: a64c6f66e56a
Create Date: 2020-12-04 10:38:58.191481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2896a2b84175'
down_revision = 'a64c6f66e56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
