"""New revihf

Revision ID: 2de68000dc87
Revises: 6e2f4991b032
Create Date: 2021-01-14 20:49:34.103743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de68000dc87'
down_revision = '6e2f4991b032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
