"""New revihf8fft

Revision ID: 32a1ae7134e2
Revises: ab0c78aab034
Create Date: 2021-01-14 21:09:24.268543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a1ae7134e2'
down_revision = 'ab0c78aab034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
