"""New revihf8

Revision ID: 336390e2d82c
Revises: 2de68000dc87
Create Date: 2021-01-14 20:55:56.566792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336390e2d82c'
down_revision = '2de68000dc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
