"""ratin3g06

Revision ID: 3c92f28efc06
Revises: 0a71fbe3a096
Create Date: 2020-12-03 21:19:01.427618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c92f28efc06'
down_revision = '0a71fbe3a096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
