"""New revision6609

Revision ID: 5719a8391766
Revises: d9d07f80b529
Create Date: 2020-12-04 10:50:50.188152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5719a8391766'
down_revision = 'd9d07f80b529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rating', ['rating_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rating_id')
    # ### end Alembic commands ###
