"""543ytjhfgfjh

Revision ID: 6a608eea07fa
Revises: 1c3d22787f00
Create Date: 2021-01-14 22:06:43.304663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a608eea07fa'
down_revision = '1c3d22787f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
