"""New revih

Revision ID: 6e2f4991b032
Revises: 7bda6cc67002
Create Date: 2021-01-14 20:47:37.334610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2f4991b032'
down_revision = '7bda6cc67002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
