"""New revihf8fftg

Revision ID: 73d801344f7b
Revises: 32a1ae7134e2
Create Date: 2021-01-14 21:10:46.488248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d801344f7b'
down_revision = '32a1ae7134e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
