"""New revision3

Revision ID: 7527f3ca4de1
Revises: 2166efde81cd
Create Date: 2020-11-26 15:53:45.502702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7527f3ca4de1'
down_revision = '2166efde81cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master')
    # ### end Alembic commands ###
