"""tr

Revision ID: 7bda6cc67002
Revises: be78d7ac360b
Create Date: 2020-12-26 19:21:04.512098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bda6cc67002'
down_revision = 'be78d7ac360b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
