"""New revihf8fftggf

Revision ID: 805ea5d0f8b4
Revises: 73d801344f7b
Create Date: 2021-01-14 21:23:45.256014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805ea5d0f8b4'
down_revision = '73d801344f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
