"""543y

Revision ID: 8a94a135477f
Revises: eb3873f6159b
Create Date: 2021-01-14 21:29:07.932057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a94a135477f'
down_revision = 'eb3873f6159b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
