"""098y

Revision ID: 8d51d51434a1
Revises: 1a0e81c95341
Create Date: 2021-01-14 22:10:23.590334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d51d51434a1'
down_revision = '1a0e81c95341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
