"""543ytjh

Revision ID: a286e4d95b28
Revises: 8a94a135477f
Create Date: 2021-01-14 21:51:44.695640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a286e4d95b28'
down_revision = '8a94a135477f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
