"""New revision5

Revision ID: a64c6f66e56a
Revises: 3c92f28efc06
Create Date: 2020-12-04 10:37:07.971338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c6f66e56a'
down_revision = '3c92f28efc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
