"""New revihf8ff

Revision ID: ab0c78aab034
Revises: 336390e2d82c
Create Date: 2021-01-14 21:02:22.383798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0c78aab034'
down_revision = '336390e2d82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
