"""New revision4446gf

Revision ID: be78d7ac360b
Revises: d9d7abd2fb06
Create Date: 2020-12-21 19:41:28.129682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be78d7ac360b'
down_revision = 'd9d7abd2fb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
