"""twoo

Revision ID: d461a29c2e31
Revises: e4488bafeba4
Create Date: 2020-12-09 12:55:06.634490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd461a29c2e31'
down_revision = 'e4488bafeba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_time', sa.Column('phone_owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_time', 'phone_owner')
    # ### end Alembic commands ###
