"""New revision4446g

Revision ID: d9d7abd2fb06
Revises: ff1b9439f391
Create Date: 2020-12-21 19:39:39.014778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d7abd2fb06'
down_revision = 'ff1b9439f391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_title', sa.Integer(), nullable=True))
    op.drop_constraint('users_category_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'category', ['category_title'], ['title'])
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_category_id_fkey', 'users', 'category', ['category_id'], ['id'])
    op.drop_column('users', 'category_title')
    # ### end Alembic commands ###
