"""ferst

Revision ID: e4488bafeba4
Revises: 2047eccea9a8
Create Date: 2020-12-07 20:52:18.170244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4488bafeba4'
down_revision = '2047eccea9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_time', sa.Column('master_confirm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_time', 'master_confirm')
    # ### end Alembic commands ###
