"""543

Revision ID: eb3873f6159b
Revises: 805ea5d0f8b4
Create Date: 2021-01-14 21:26:34.566664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3873f6159b'
down_revision = '805ea5d0f8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
