"""New revision4446

Revision ID: ff1b9439f391
Revises: 1b61c908a36b
Create Date: 2020-12-21 19:37:53.030941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1b9439f391'
down_revision = '1b61c908a36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_slug', sa.Integer(), nullable=True))
    op.drop_constraint('users_category_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'category', ['category_slug'], ['title'])
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_category_id_fkey', 'users', 'category', ['category_id'], ['id'])
    op.drop_column('users', 'category_slug')
    # ### end Alembic commands ###
